export const mockJobData = [
  {
    open_datetime: "2025-01-15 08:30",
    workcenter: "WC-001",
    project_name: "โครงการ A",
    document_no: "JB-2025-001",
    pm_order: "PM-001",
    planned_start: "2025-01-15 09:00",
    planned_end: "2025-01-15 17:00",
    duration_hours: 8,
    customer: "ลูกค้า A",
    site: "Site-01",
    branch: "สาขากรุงเทพ",
    location: "อาคาร A ชั้น 3",
    address: "123 ถนนสุขุมวิท",
    postal_code: "10110",
    ip_cbx: "192.168.1.1",
    phone: "02-xxx-xxxx",
    latest_task: "Task 5",
    task_text: "ตรวจสอบอุปกรณ์",
    pm_officer: "สมชาย ใจดี",
    type: "CM",
    opener: "วิไล รักษ์ดี",
    pm_detail: "ตรวจสอบระบบไฟฟ้า",
    customer_name: "บริษัท ABC จำกัด",
    customer_phone: "081-xxx-xxxx",
    op_start_datetime: "2025-01-15 09:15",
    op_fix: "เปลี่ยนสายไฟ",
    op_fixer: "ช่างสมศักดิ์",
    technician_dept: "ฝ่ายไฟฟ้า",
    op_complete_datetime: "2025-01-15 16:00",
    customer_accept_op: "ยอมรับ",
    grad_teleport: "A",
    equipment_changed: "ใช่",
    removed_equipment: "สายไฟเก่า 5 เมตร",
    installed_equipment: "สายไฟใหม่ 5 เมตร",
    failure_cause: "สายไฟชำรุด",
    notifier_name: "วิไล รักษ์ดี",
    acceptor_name: "สุชาติ มั่นคง",
    delay_cause_teleport: "-",
    duration: "7 ชม.",
    grad_pm: "A",
    customer_comment: "พอใจ",
    dial_on: "On",
    all_downtime: "2 ชม.",
    planner_grp: "PG-01",
    dial_onsite_sla: "In SLA",
  },
  // เพิ่มแถวที่ 2
  {
    open_datetime: "2025-01-16 10:00",
    workcenter: "WC-002",
    project_name: "โครงการ B",
    document_no: "JB-2025-002",
    pm_order: "PM-002",
    planned_start: "2025-01-16 11:00",
    planned_end: "2025-01-16 18:00",
    duration_hours: 7,
    customer: "ลูกค้า B",
    site: "Site-02",
    branch: "สาขาเชียงใหม่",
    location: "อาคาร B ชั้น 1",
    address: "456 ถนนนิมมาน",
    postal_code: "50200",
    ip_cbx: "192.168.1.2",
    phone: "053-xxx-xxxx",
    latest_task: "Task 3",
    task_text: "ซ่อมแอร์",
    pm_officer: "สุดา ขยันดี",
    type: "PM",
    opener: "มานะ ตั้งใจ",
    pm_detail: "PM ระบบทำความเย็น",
    customer_name: "บริษัท XYZ จำกัด",
    customer_phone: "089-xxx-xxxx",
    op_start_datetime: "2025-01-16 11:30",
    op_fix: "เติมน้ำยาแอร์",
    op_fixer: "ช่างประสิทธิ์",
    technician_dept: "ฝ่ายเครื่องกล",
    op_complete_datetime: "2025-01-16 17:30",
    customer_accept_op: "ยอมรับ",
    grad_teleport: "B",
    equipment_changed: "ไม่",
    removed_equipment: "-",
    installed_equipment: "-",
    failure_cause: "น้ำยาแอร์หมด",
    notifier_name: "มานะ ตั้งใจ",
    acceptor_name: "กมลา รักสะอาด",
    delay_cause_teleport: "รถติด",
    duration: "6 ชม.",
    grad_pm: "B",
    customer_comment: "ดีมาก",
    dial_on: "On",
    all_downtime: "1 ชม.",
    planner_grp: "PG-02",
    dial_onsite_sla: "In SLA",
  },
];